services:
  nginx-proxy:
    build: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/flossed_falcon.conf:/tmp/default.conf
      # alternatively, if deployment with TLS is desired, make sure to fill the files in ./nginx/ssl
      # - ./nginx/flossed_falcon_ssl.conf:/tmp/default.conf
      # - ./nginx/ssl:/opt/ssl_certificates
    environment: 
      - FALCON_SERVER_ADDR=flossed-falcon:8000
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flossed-falcon
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/health-check || exit 1"]
      interval: 600s
      timeout: 600s
      retries: 3
    command: /app/start.sh
  flossed-falcon:
    build: flossed-falcon
    restart: always
    volumes:
      - ./data/malpedia_flossed.json:/data/malpedia_flossed.json
      - ./logs:/var/log/
    ports: 
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/falcon-health-check || exit 1"]
      interval: 600s
      timeout: 600s
      retries: 3
    command: python main.py
